### ISSUE TITLE
Leaving out 2 pages of content

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Political-Science#1]
Hello,
So the PolySci site has 2 pages of content that I will not be adding.

1) **[Graduate Students](http://www.cla.temple.edu/politicalscience/graduate/current-students/)**- Literally just a list of grad students since 1982
2) **[Hire a PhD](http://www.cla.temple.edu/politicalscience/graduate/hire-a-ph-d/)**- Literally just a list of grad students and their dissertations.

I don't fell as if these two pages are necessary, see it as extra clutter.

**Comment by tu-chill** [comment]
The lists seem harmful in that it adds to the noise. In the future I'd be open to testing the usefulness of these list behind a form where we can capture some information from the users who take the time to download lists like this. If we do the form thing who would want the data?

**Comment by CVE82** [comment]
The data would be useful for graduate chairs..

**Comment by tu-chill** [comment]
noted
