### ISSUE TITLE
Image needed home

### ISSUE THREAD

**Issue by saracurnow** [TULiberalArts/Political-Science#10]
Homepage needs an image

**Comment by CVE82** [comment]
Please assign to Zac Mcgroraty with the label "Visual Design" so he know that this program needs one.

**Comment by saracurnow** [comment]
Virtual Design

(Hope I did this right!)

**Comment by CVE82** [comment]
Zac let me know when it's good to go and I will put it on the home page. Thanks!

**Comment by ZMcGroarty** [comment]
Hey,

Lets try this one. It might not work with the white text but I wanted to give it a shot anyway.

Thanks

![hero_politicalscience-min](https://user-images.githubusercontent.com/15017242/27336783-9ae23520-559e-11e7-8ded-c5ab7ec80f4d.png)

**Comment by CVE82** [comment]
Thanks I will get it up in a few minutes!

**Comment by ZMcGroarty** [comment]
recropped

![hero_politicalscience-min](https://user-images.githubusercontent.com/15017242/27338707-eefe001c-55a3-11e7-8625-96bfbdad5f69.png)

**Comment by CVE82** [comment]
Sweet thanks!

**Comment by CVE82** [comment]
Hero set! =D
