### ISSUE TITLE
Primary Nav | getting 404s

### ISSUE THREAD

**Issue by mayshays** [TULiberalArts/Political-Science#2]
Undergraduate, Graduate, Research, Next Stops are not available on dev server. Seems to be the common html proofer failing on faculty https://travis-ci.org/TULiberalArts/Political-Science

**Comment by tu-chill** [comment]
Adding slashes to meta and navigation seem to work. I think I think the trailing slash is ugly. There is a good chance that I am the only one on the face of the earth who would have an opinion about the trailing slash on a URL.
