### ISSUE TITLE
Content that will not be migrated

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Political-Science#5]
The following content was not migrated, it does not pertain to prospective students and should be housed elsewhere or will be placed on the site somehow during Phase II:
- PH.D Placement- There is no need for a list of PH.D placements since 1998
- Hire a PH.D- There is no need for this list, it can be shared internally if they wish. 
- Current MPP Students- As for now, no graduate pages are going to contain lists and bios of graduate students. 
- Current Students-  As for now, no pages are going to contain lists and bios of students

**Comment by tu-chill** [comment]
seen
