### ISSUE TITLE
Meta-data Content

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Political-Science#6]
The home page needs:

- [x] meta-description: 100- 150 characters

- [ ] meta-keywords: 3 or 4 unique for this page

**Comment by CVE82** [comment]
The home page still needs a meta-description and meta keywords.

**Comment by saracurnow** [comment]
Added meta-description to each page. The meta data looks sloppy in prose, not sure about the spacing &c. Can work on keywords next but would be good if someone could check to see if I'm doing the descriptions right. Thanks!

**Comment by tu-chill** [comment]
meta descriptions look great! thanks. we can use readability.io to pull keywords once the content is complete.

**Comment by saracurnow** [comment]
Woo! Sounds like a plan.

**Comment by CVE82** [comment]
Keywords added to all pages per readable.io.
