### ISSUE TITLE
Undergraduate Page content

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Political-Science#9]
Hey WC when you get back on Wed 6/21 please take a look at the content on this page. I think the last half of the page with handbook resources etc. need to be pulled from that page. Thanks!

**Comment by saracurnow** [comment]
Joe and I are going to talk about the poli sci content today. Already planning to suggest this handbook content gets pulled or placed elsewhere--stay tuned!

**Comment by tu-chill** [comment]
I'm assuming this is not an issue anymore
